Config/cumin (#3)
* config.yml -> config.cumin

* doc

diff --git a/manga-check b/manga-check
--- a/manga-check
+++ b/manga-check
@@ -8,43 +8,28 @@ usage() {
 Usage:
   manga-check init
   manga-check check
+  manga-check run
 EOM
   exit
 }
 
-config() {
-  cat config.yml |
-    sed '/^#/d; s/[ \t]#.*//g' |
-    awk '
-      function flush() {
-        if (name != "" && url != "" && type != "" && pattern != "") {
-          print name
-          print url
-          print type
-          print pattern
-          print notify_url == "" ? url : notify_url
-        }
-        name = ""
-        url = ""
-        notify_url = ""
-        type = ""
-        pattern = ""
-      }
-      /^-/ { flush() }
-      /^[- ]*name *:/ { name = $0 }
-      /^[- ]*url *:/ { url = $0 }
-      /^[- ]*notify_url *:/ { notify_url = $0 }
-      /^[- ]*html *:/ {
-        type = "html"
-        pattern = $0
-      }
-      /^[- ]*json *:/ {
-        type = "json"
-        pattern = $0
-      }
-      END { flush() }
-    ' |
-      sed 's/^[- ]*[a-zA-Z0-9_]* *:  *//g'
+loginfo() {
+  if [ $# -eq 0 ]; then
+    header="[$(date)] "
+    cat | sed "s/^/$header/" >&2
+  else
+    echo "[$(date)] $@" >&2
+  fi
+}
+
+items() {
+  cat config.cumin | cuminc -T json | jq -cM .[]
+}
+
+jsonvalue() {
+  QUERY="$1"
+  JSONDATA="$2"
+  echo "$JSONDATA" | jq -r "$QUERY"
 }
 
 hashcode() {
@@ -72,16 +57,17 @@ extract() {
 init() {
   [ -d $CACHE_DIR ] && rm -r $CACHE_DIR
   mkdir -p $CACHE_DIR
-  config |
-    while read name; do
-      read url
-      read ty
-      read pat
-      read notify_url
-      F="$CACHE_DIR/$(echo $url $pat | hashcode)"
+  items |
+    while read json; do
+      name="$(jsonvalue .name "$json")"
+      url="$(jsonvalue .url "$json")"
+      ty="$(jsonvalue .type "$json")"
+      pat="$(jsonvalue .pattern "$json")"
+      format="$(jsonvalue .format "$json")"
+      F="$CACHE_DIR/$(echo $name | hashcode)"
       extract "$url" "$ty" "$pat" > $F
-      cat <<EOM
-[$(date)] init
+      loginfo <<EOM
+---
 Name: $name
 Url: $url
 Extract Type: $ty
@@ -97,41 +83,41 @@ EOM
 }
 
 check() {
-  config |
-    while read name; do
-      read url
-      read ty
-      read pat
-      read notify_url
+  items |
+    while read json; do
+      name="$(jsonvalue .name "$json")"
+      url="$(jsonvalue .url "$json")"
+      ty="$(jsonvalue .type "$json")"
+      pat="$(jsonvalue .pattern "$json")"
+      format="$(jsonvalue .format "$json")"
 
-      echo "$url"
+      loginfo "---"
+      loginfo "Checking $name $url"
+
       http_status="$(http_code "$url")"
+      loginfo "http_status = $http_status"
+
       case "$http_status" in
         2* )
           F="$CACHE_DIR/$(echo $name | hashcode)"
+          loginfo "Cache file is $F"
           F_NEW="$CACHE_DIR/$(echo $name | hashcode)-new"
           extract "$url" "$ty" "$pat" > $F_NEW
-          echo -n "[$(date)] $url ... "
           if diff $F $F_NEW > /dev/null; then
-            echo "No Update"
+            loginfo "No Update"
           else
-            echo "Updated!!"
+            loginfo "Updated!!"
             diff $F $F_NEW
-            notify "$name" "$notify_url" "$F_NEW"
           fi
           mv $F_NEW $F
           ;;
 
         * )
-          echo "Skip $url (http_status=$http_status)"
+          loginfo "Failed $url (http_status=$http_status)"
           ;;
       esac
 
     done
-}
-
-notify() {
-    echo "$@"
 }
 
 run() {
